spring:
  application:
    name: ms-restaurant

  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: appuser
    password: AppPass!123
    driver-class-name: org.postgresql.Driver



  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
    enabled: true
    parameters:
      useSystemViews: false


  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379



  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081
